# Generated by Django 3.2.4 on 2021-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moika', '0002_auto_20210608_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='events',
            name='main_photo',
            field=models.ImageField(upload_to='images/main'),
        ),
    ]
