# Generated by Django 3.2.4 on 2021-06-08 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moika', '0004_alter_events_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.TextField()),
                ('description', models.TextField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='moika.events')),
            ],
        ),
    ]
